### ISSUE TITLE
Please do not put AppImage into a zip archive

### ISSUE THREAD

**Issue by probonopd** [Tilagiho/eNoseAnnotator#7]
Please do not put AppImage into a zip archive. The reasons are described at https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#common-mistake.

Thank you very much.

**Comment by Tilagiho** [comment]
Thanks for the suggestion. From c9ac1c4abefd882dd317924a0200933d49a3044b on the AppImage is not archived before uploading anymore.

**Comment by probonopd** [comment]
Thank you very much. :+1:
